### ISSUE TITLE
Now that we have UNKNOWN_MESSAGE

### ISSUE THREAD

**Issue by pkivolowitz** [pkivolowitz/pas#17]
Maybe pas should return that is deserialization fails instead of throwing exceptions?

**Comment by LOZORD** [comment]
I agree, IMO throwing exceptions is never preferable to returning a value that represents an error. For example, with HTTP, you would return something with a status of `40x`, meaning "hey, we got something from you, but it didn't make sense".

A practice I've seen before is to use something like:

```proto
message ResponsePayload {
  Status status = 1;
  Data data = 2;
}
```

If `status` is not a "success" value, then there is no need to look at the returned data (or assume that the remote call was a success).

**Comment by pkivolowitz** [comment]
Consider it done.
